# Adding search parameters on Search Books
openapi: 3.0.3

info:
  title: Bookshop
  version: "1.0"
  description: |
    ![OpenAPI Logo](https://avatars3.githubusercontent.com/u/16343502?v=3&s=100)

    A demo _API_ to **discover** the **_[OpenAPI Specification](https://www.openapis.org/)_**.

servers:
  - description: The base path for all resources
    url: /bookshop/v1

paths:
  /books:
    get:
      summary: Search books
      operationId: searchBooks
      parameters:
        # A parameter defined inline
        - name: author
          # This is a query parameter GET /books?author=arnaud
          in: query
          # It is recommended to avoid required query parameters, makes the API less user friendly
          required: false
          # Sometimes the name and schema are not enough, neveer hesitate to take advantage of descriptions to provide more information
          description: "Complete or partial author name, , can be typed phonetically"
          # Parameters use schema like response bodies
          schema:
            # Parameter can take advantage of reusable schemas
            $ref: "#/components/schemas/QueryParameterString"
        # Like schemas, parameters can be defined in components
        # Allows to use the same definition across operations
        - $ref: "#/components/parameters/Title"
      responses:
        "200":
          description: Books matching search parameters
          content:
            application/json:
                schema:
                  $ref: "#/components/schemas/Books"
                examples:
                  SomeBooks:
                    summary: A few books found
                    value:
                      data:
                        - id: "9781617295102"
                          isbn: "9781617295102"
                          title: "The Design of Web APIs"
                          price: 
                            value: 44.99
                            currency: "USD"
                          authors:
                              - id: "12345"
                                firstName: "Arnaud"
                                lastName: "Lauret"
                          stars: 4.4
                        - id: " 9780137355631"
                          isbn: " 9780137355631"
                          title: "Principles of Web API Design"
                          price: 
                            value: 44.99
                            currency: "USD"
                          authors:
                              - id: "12346"
                                firstName: "James"
                                lastName: "Higginbotham"
                          stars: 4.7

components:
  schemas:
    BookId:
      type: string
      pattern: (978|979)([0-9]{10})
      description: Book's [ISBN 13](https://www.isbn-international.org/content/what-isbn) (a standard book identifier)
    Amount:
      properties:
        value:
          type: number
          minimum: 0
        currency:
          type: string
          description: An ISO 4217 currency code
          minLength: 3
          maxLength: 3
          enum:
            - USD
            - EUR
      required:
        - value
        - currency
    Authors:
      type: array
      minItems: 1
      items:
        properties:
          id:
            type: string
            description: A unique id identifying an author
          firstName:
            type: string
          middleName:
            type: string
          lastName:
            type: string
        required:
          - id
          - firstName
          - lastName
    BookSummary:
      properties:
        id:
          $ref: "#/components/schemas/BookId"
        isbn:
          $ref: "#/components/schemas/BookId"
        title:
          type: string
          minLength: 1
          maxLength: 100
        price:
          $ref: "#/components/schemas/Amount"
        authors:
          $ref: "#/components/schemas/Authors"
        stars:
          type: number
          exclusiveMinimum: true
          minimum: 0
          maximum: 5
      required:
        - id
        - isbn
        - title
        - price
        - authors
    Books:
      type: object  
      properties:
        data:
          type: array
          minItems: 0
          maxItems: 100
          items:
            $ref: "#/components/schemas/BookSummary"
    # This schema is used in a query parameter
    QueryParameterString:
      type: string
      maxLength: 100
      minLength: 1
  # Parameters holds reusable parameters
  parameters:
    Title:
      name: title
      in: query
      description: "Complete or partial title, can be typed phonetically"
      required: false
      schema:
        $ref: "#/components/schemas/QueryParameterString"
